# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.28
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
enable_checklog_odoo: true
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Odoo
odoo_version: 17.0
org_name: Out of reality
org_slug: out-of-reality
rebel_module_groups: []
repo_description: Mechatronics final project
repo_name: Out of reality
repo_slug: out-of-reality
repo_website: https://github.com/out-of-reality/out-of-reality
use_pyproject_toml: true
use_ruff: true
